// Seed topics for autonomous prediction generation. 30 themes, each with a
// short brief the question-drafting model uses as context.

export const TOPICS = [
  { id: "ai",        title: "Artificial Intelligence", hint: "frontier labs, benchmarks, agents, regulation" },
  { id: "climate",   title: "Climate & Environment",   hint: "temp anomalies, disasters, policy, renewables" },
  { id: "geo",       title: "Geopolitics",             hint: "elections, alliances, trade blocs, conflicts" },
  { id: "markets",   title: "Markets & Economy",       hint: "indices, recessions, rates, commodities" },
  { id: "space",     title: "Space Exploration",       hint: "launches, landings, missions, commercial space" },
  { id: "health",    title: "Health & Medicine",       hint: "therapies, approvals, pandemics, wearables" },
  { id: "energy",    title: "Energy",                  hint: "solar, nuclear, grid, oil" },
  { id: "crypto",    title: "Crypto & Finance",        hint: "bitcoin, ETFs, stablecoins, regulation" },
  { id: "tech",      title: "Consumer Tech",           hint: "smartphones, AR/VR, wearables, AI products" },
  { id: "culture",   title: "Culture & Media",         hint: "films, music, streaming, viral trends" },
  { id: "science",   title: "Science & Research",      hint: "publications, prizes, paradigm shifts" },
  { id: "biotech",   title: "Biotech & Longevity",     hint: "gene editing, longevity, synthetic biology" },
  { id: "robotics",  title: "Robotics & Automation",   hint: "humanoids, warehouses, logistics" },
  { id: "transport", title: "Transportation",          hint: "EVs, autonomy, aviation, rail" },
  { id: "education", title: "Education",               hint: "university, AI tutors, credentials" },
  { id: "labor",     title: "Work & Labor",            hint: "remote work, unions, automation impact" },
  { id: "demo",      title: "Demographics",            hint: "birth rates, migration, aging" },
  { id: "security",  title: "Security & Defense",      hint: "cyber, drones, nuclear, alliances" },
  { id: "sports",    title: "Sports",                  hint: "records, championships, new leagues" },
  { id: "gaming",    title: "Gaming",                  hint: "engines, AI NPCs, platforms" },
  { id: "art",       title: "Art & Design",            hint: "generative art, auctions, exhibitions" },
  { id: "food",      title: "Food & Agriculture",      hint: "lab meat, vertical farms, famines" },
  { id: "web3",      title: "Web3 & Decentralization", hint: "L2s, DePIN, DAOs" },
  { id: "privacy",   title: "Privacy & Surveillance",  hint: "cameras, data laws, encryption" },
  { id: "policy",    title: "Policy & Regulation",     hint: "AI act, antitrust, tax" },
  { id: "nature",    title: "Nature & Wildlife",       hint: "extinctions, conservation" },
  { id: "oceans",    title: "Oceans",                  hint: "ice, currents, acidification" },
  { id: "housing",   title: "Housing & Real Estate",   hint: "prices, construction, rent" },
  { id: "mobility",  title: "Urban Mobility",          hint: "transit, ride-hail, bikes" },
  { id: "longevity", title: "Longevity",               hint: "life expectancy, aging breakthroughs" },
];

export const HORIZONS = [
  { id: "1w",   label: "1 week",    days: 7 },
  { id: "1m",   label: "1 month",   days: 30 },
  { id: "6m",   label: "6 months",  days: 180 },
  { id: "1y",   label: "1 year",    days: 365 },
  { id: "3y",   label: "3 years",   days: 1095 },
  { id: "5y",   label: "5 years",   days: 1825 },
  { id: "10y",  label: "10 years",  days: 3650 },
  { id: "50y",  label: "50 years",  days: 18250 },
  { id: "100y", label: "100 years", days: 36500 },
];
